name: Commit Files

on: 
  #schedule: # execute automatically 2 times every day.
  #  - cron: "10 10,22 * * *"
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Checkout Cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-1
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.5'

    - name: 'Install requirements'
      run: pip install -r ./requirements.txt

    - name: Run Python script
      run: python main.py ${{ secrets.line_token1 }}

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Add generated files' || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
